### PR TITLE
MM3D Import Fix

### PR DESCRIPTION
**Pull request by andyeder**
Added [potentially] useful function for returning Yaw, Pitch, Roll angles, fixed a couple of spelling mistakes and removed an unnecessary return statement from the updateMatrix function (which was preventing MM3D files from importing correctly in some cases).

### CODE REVIEW

**Comment by Kneesnap** [comment]
Isn't this redundant compared to the methods individually calculating this?

**Comment by Kneesnap** [comment]
Does this completely fix the issue? Can you verify that frame 0 for DES_BIRD1.XAR in THEME_DES1.WAD works properly? That model in particular was especially broken.

**Comment by andyeder** [comment]
> Isn't this redundant compared to the methods individually calculating this?

I put it in whilst testing a few things out. Might leave it just for now as things may not be fixed yet and it could prove useful.

**Comment by andyeder** [comment]
> Does this completely fix the issue? Can you verify that frame 0 for DES_BIRD1.XAR in THEME_DES1.WAD works properly? That model in particular was especially broken.

Not sure - could still be broken. Until I can find more time to dig deeper there could well be more issues yet to find. I'll assume it still needs work and try and find some time as soon as I can.

**Comment by andyeder** [comment]
Closing pull request without merge until further investigations have been carried out.

**Pull request closed without merging**
